# Configuration for JoinAnimations
# Will add more animations soon.

# Choose the animation to play when a player joins.
# Available options: "totem" (Totem of Undying) or "guardian" (Guardian Curse).
# join-animation: "totem"
join-animation: totem
